ca-cwds/perry

build.gradle
config/perry-prod.yml
jwt-security/src/main/java/gov/ca/cwds/security/jwt/JCEKSKeyProvider.java
jwt-security/src/main/java/gov/ca/cwds/security/jwt/JwtService.java
src/main/java/gov/ca/cwds/config/OAuthConfiguration.java
src/main/java/gov/ca/cwds/service/OauthLoginService.java
src/main/java/gov/ca/cwds/service/SAFService.java
src/main/java/gov/ca/cwds/service/oauth/SafUserInfoTokenService.java
src/test/java/gov/ca/cwds/service/OauthLoginServiceTest.java
src/test/java/gov/ca/cwds/service/OauthLoginServiceTestConf.java

Add accessToken as a part of Payload of JWTToken

150894837 link perry and saf token

---

shiro-security/shiro-v2.ini

#150894576 Perry: token invalidation callback

---

src/main/java/gov/ca/cwds/service/SAFService.java
src/test/java/gov/ca/cwds/service/SAFServiceTest.java
src/test/java/gov/ca/cwds/service/TokenLoginServiceTest.java
src/test/java/gov/ca/cwds/service/TokenLoginServiceTestConf.java

150894576 logout callback

---

api-security/src/main/java/gov/ca/cwds/security/utils/PrincipalUtils.java

TPT3-37 add PrincipalUtils from development branch

---

api-security-test-support/src/main/resources/default-principal.json
build.gradle

https://osi-cwds.atlassian.net/browse/CALS-5199

CALS-5199: default principal updated in api-security-test-support

---

api-security/src/test/java/gov/ca/cwds/security/AbstractApiSecurityTest.java
api-security/src/test/java/gov/ca/cwds/security/ApiSecurityTest.java
api-security/src/test/java/gov/ca/cwds/security/realm/JwtRealmTest.java

Test support

---

.github/PULL_REQUEST_TEMPLATE.md
api-security-common/build.gradle
api-security-common/src/main/java/gov/ca/cwds/security/realm/PerryAccount.java
api-security-test-support/build.gradle
api-security/build.gradle
build.gradle
jwt-security/build.gradle

- [CALS-5654: Enforce IBM Security Guide requirements regarding Client Search in Get Facility Children API in CALS API](https://osi-cwds.atlassian.net/browse/CALS-5654)
toString method added to PerryAccount so it will be printed properly in the logs. Artifactory URL changed to current.
No custom code written. Apache Commons library used to generate string representation of the object.
What types of changes does your code introduce? Put an `x` in all the boxes that apply:
N/A
N/A

CALS-5654: toString added to PerryAccount. Artifactory URL updated.

---

src/main/java/gov/ca/cwds/PerryProperties.java
src/main/java/gov/ca/cwds/config/FormLoginConfiguration.java
src/main/java/gov/ca/cwds/config/LoginServiceValidatorFilter.java
src/main/java/gov/ca/cwds/rest/api/LoginResource.java
src/main/java/gov/ca/cwds/service/WhiteList.java

- [CALS-5662: Perry v2: Add default logout success page](https://osi-cwds.atlassian.net/browse/CALS-5662)

CALS-5662: callback is optional

---

config/perry-preview-template.yml

- [CALS-5852: Name of Story](https://osi-cwds.atlassian.net/browse/CALS-5852)

preview fix

---

src/main/java/gov/ca/cwds/service/UserAuthorizationService.java

- [CALS-5886: Perry: DataIntegrityViolationException on NON-RACF account login(INT only)](https://osi-cwds.atlassian.net/browse/CALS-5886)

racfid length validation

---

src/main/java/gov/ca/cwds/service/LoginServiceImpl.java
src/main/java/gov/ca/cwds/service/sso/OAuth2Service.java
src/main/java/gov/ca/cwds/service/sso/SsoService.java
src/main/java/gov/ca/cwds/service/sso/custom/form/FormService.java

- [DOE-3127: Name of Story](https://osi-cwds.atlassian.net/browse/DOE-3127)

DOE-3127: bug fix

---

src/main/java/gov/ca/cwds/service/sso/OAuth2Service.java

- [CALS-5923](https://osi-cwds.atlassian.net/browse/CALS-5923)

CALS-5923: bug fix

---

integration-tests/build.gradle
integration-tests/src/test/java/gov/ca/cwds/test/TestDevMode.java

- https://osi-cwds.atlassian.net/browse/AARA-227
System parameters passed to test when started from gradle

AARA-227: system parameters passed to test when started from gradle

---

build.gradle

- https://osi-cwds.atlassian.net/browse/COG-30
New version of CWDS Data Model with updated permissions

COG-30: new version of CWDS Data Model with updated permissions

---

src/main/resources/static/js/script.js

JSON example on login page updated to support new roles and privileges

JSON example on login page updated to support new roles and privileges

---

config/idm.groovy
src/main/java/gov/ca/cwds/data/auth/CwsOfficeDao.java
src/main/java/gov/ca/cwds/data/auth/StaffPersonDao.java
src/main/java/gov/ca/cwds/data/auth/UserIdDao.java
src/main/java/gov/ca/cwds/idm/IdmResource.java
src/main/java/gov/ca/cwds/idm/dto/UsersSearchParameter.java
src/main/java/gov/ca/cwds/idm/service/CognitoIdmService.java
src/main/java/gov/ca/cwds/idm/service/CognitoServiceFacade.java
src/main/java/gov/ca/cwds/idm/service/IdmService.java
src/main/java/gov/ca/cwds/idm/util/UsersSearchParametersUtil.java
src/main/java/gov/ca/cwds/service/UserAuthorizationService.java
src/main/java/gov/ca/cwds/service/scripts/IdmMappingScript.java
src/test/java/gov/ca/cwds/service/UserAuthorizationServiceTest.java

- [COG-29: ListUsers (idm) service implementation](https://osi-cwds.atlassian.net/browse/COG-29)
- [COG-27: Search for Users (idm) service](https://osi-cwds.atlassian.net/browse/COG-27)
idm list of users service implementation
search for users by lastname, starts with  approach

NEW: COG-29, COG-27

---

config/cognito.groovy

mapping-fix

---

src/main/java/gov/ca/cwds/rest/api/LoginResource.java
src/test/java/gov/ca/cwds/rest/api/LoginResourceTest.java

- [AARA-390: Perry: fix Perry form callback URL](https://osi-cwds.atlassian.net/browse/AARA-390)

AARA-390: fix Perry form callback URL

---

config/default.groovy

- [AARA-268: Name of Story](https://osi-cwds.atlassian.net/browse/AARA-268)

AARA-268: email attr fix

---

src/main/java/gov/ca/cwds/idm/service/CognitoUtils.java
src/test/java/gov/ca/cwds/idm/service/CognitoUtilsTest.java

Cognito attribute search is made case insensitive.
- [x ] I have included unit tests 
- [x ] Bug fix (non-breaking change which fixes an issue)

Cognito attribute search is made case insensitive.

---

Jenkinsfile-complete.groovy

Reduced number of parallel threads for Integration tests to eliminate potential errors

Reduced number of parallel threads for Integration tests

---

Jenkinsfile-complete.groovy

Jenkins Pipeline fix

---

src/main/java/gov/ca/cwds/rest/api/LoginResource.java
src/test/java/gov/ca/cwds/rest/api/LoginResourceTest.java

- [TSN-403: "Unknown error" message received on login](https://osi-cwds.atlassian.net/browse/TSN-403)

TSN-403: fragment in callback and relative callback support

---

docker-cap-tests/Readme.md

- [COG-260 CAP-api performance tests docker image](https://osi-cwds.atlassian.net/browse/COG-260)
- [X ] Bug fix (non-breaking change which fixes an issue)

COG-260: Readme fixed

---

src/main/java/gov/ca/cwds/idm/IdmResource.java
src/main/java/gov/ca/cwds/idm/dto/CognitoUserPage.java
src/main/java/gov/ca/cwds/idm/dto/UsersPage.java
src/main/java/gov/ca/cwds/idm/dto/UsersSearchParameter.java
src/main/java/gov/ca/cwds/idm/service/IdmService.java
src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacade.java
src/main/java/gov/ca/cwds/idm/util/UsersSearchParametersUtil.java
src/test/java/gov/ca/cwds/idm/IdmResourceTest.java
src/test/resources/fixtures/idm/get-users/all-valid.json
src/test/resources/fixtures/idm/get-users/search-valid.json

- [COG-268: Initial full index job for cap users](https://osi-cwds.atlassian.net/browse/COG-268)
idm/getUsers REST method refactored to return all users by pages

COG-268 getUsers refactored to return all users by pages

---

src/main/java/gov/ca/cwds/service/sso/OAuth2Service.java

- [AARA-495: Perry token validation fails after 1 hour](https://osi-cwds.atlassian.net/browse/AARA-495)

AARA-495: refresh bug fix

---

build.gradle

- [COG-327: permissions dictionary - backend](https://osi-cwds.atlassian.net/browse/COG-327)
Bug with schema is fixed in data model liquibase script
Integration tests pass successfully

COG-327: fix permissions liquibase

---

docker-perry/entrypoint.sh
jwt-security/src/test/java/gov/ca/cwds/security/jwt/JwtServiceTest.java
src/main/java/gov/ca/cwds/service/mfa/CognitoResponseService.java
src/main/java/gov/ca/cwds/service/mfa/model/AuthParameters.java
src/main/java/gov/ca/cwds/service/mfa/model/AuthenticationResult.java
src/main/java/gov/ca/cwds/service/mfa/model/Payload.java
src/main/java/gov/ca/cwds/service/mfa/model/RefreshRequest.java
src/main/java/gov/ca/cwds/service/mfa/model/RefreshResponse.java
src/main/java/gov/ca/cwds/service/sso/OAuth2Service.java
src/main/java/gov/ca/cwds/service/sso/custom/cognito/CognitoSsoService.java

- [COG-353: refresh fix](https://osi-cwds.atlassian.net/browse/COG-353)

COG-353: refresh fix

---

build.gradle

- [COG-327: permissions dictionary - backend](https://osi-cwds.atlassian.net/browse/COG-327)
Schema name is removed from liquibase sql

COG-327: schema is removed from sql

---

src/main/resources/templates/error.html

- [AARA-473: Make Error message on error screen visible at all times](https://osi-cwds.atlassian.net/browse/AARA-473)

AARA-473: Make Error message on error screen visible at all times

---

jmeter/PerryMFALoginPOC.jmx
jmeter/cognito_users_mfa.csv

- https://osi-cwds.atlassian.net/browse/COG-393
Perry MFA performance test POC using WebDriver. Jmeter can log in into Integration with hardcoded second-factor code.

COG-393: Perry MFA performance test POC using WebDriver

---

config/perry-prod.yml
src/main/java/gov/ca/cwds/idm/service/SearchService.java
src/test/java/gov/ca/cwds/idm/service/SearchServiceTest.java

- [COG-383: Update Elastic Search 'users' index using Dora REST webservice during Cognito user insert and update.](https://osi-cwds.atlassian.net/browse/COG-383)
Hot fixes for COG-383

COG 383 Hot Fixes

---

config/perry-dev.yml

-  https://osi-cwds.atlassian.net/browse/COG-383
Added default dora url for pre-int env
Added default dora url for pre-int env

COG-383 Added default dora url for pre-int environment

---

src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
src/main/java/gov/ca/cwds/idm/service/SearchService.java
src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacade.java
src/main/java/gov/ca/cwds/idm/service/cognito/util/CognitoUsersSearchCriteriaUtil.java
src/main/java/gov/ca/cwds/idm/service/cognito/util/CognitoUtils.java
src/main/java/gov/ca/cwds/util/Utils.java
src/test/java/gov/ca/cwds/idm/IdmResourceTest.java
src/test/java/gov/ca/cwds/idm/service/IdmServiceImplTest.java
src/test/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeTest.java
src/test/java/gov/ca/cwds/idm/service/cognito/util/CognitoUsersSearchCriteriaUtilTest.java
src/test/java/gov/ca/cwds/idm/service/cognito/util/CognitoUtilsTest.java
src/test/java/gov/ca/cwds/util/UtilsTest.java

- [COG-427: CAP - save email in lowercase](https://osi-cwds.atlassian.net/browse/COG-427)
Save email in lowercase in CAP

Cog 428 lowercase email dp

---

src/main/java/gov/ca/cwds/data/converter/StringToRequiredIntegerConverter.java
src/main/java/gov/ca/cwds/data/persistence/auth/CwsOffice.java
src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
src/test/java/gov/ca/cwds/data/converter/StringToRequiredIntegerConverterTest.java
src/test/java/gov/ca/cwds/idm/IdmResourceTest.java
src/test/resources/fixtures/idm/get-user/with-racfid-and-no-phone-extension.json
src/test/resources/liquibase/cms-data.xml

- [COG-448: change the interpretation of 0 value in PHONE EXTENSION to null](https://osi-cwds.atlassian.net/browse/COG-448)
change the interpretation of 0 value in PHONE EXTENSION stored to the DB to null for API clients

COG-448 extension number 0 represented as null

---

src/main/resources/static/js/script.js

CANS roles and permissions added to Perry login example JSON

---

docker-perry/Dockerfile-perry.template

Updated base docker image

---

src/main/java/gov/ca/cwds/config/TokenServiceConfiguration.java
src/main/java/gov/ca/cwds/idm/persistence/UserLogRepository.java
src/main/java/gov/ca/cwds/idm/persistence/UserLogTransactionalRepository.java
src/main/java/gov/ca/cwds/idm/service/DictionaryProvider.java
src/main/java/gov/ca/cwds/idm/service/UserLogService.java
src/test/java/gov/ca/cwds/idm/IdmResourceTest.java
src/test/java/gov/ca/cwds/idm/service/IdmServiceImplTest.java

Fix: move @Transactional annotation to concrete class

Fix move @Transactional annotation on concrete class

---

config/default.groovy
src/main/java/gov/ca/cwds/config/api/idm/Roles.java
src/test/java/gov/ca/cwds/service/scripts/CognitoMappingScriptTest.java
src/test/java/gov/ca/cwds/service/scripts/DefaultMappingCalsTest.java
src/test/java/gov/ca/cwds/service/scripts/DefaultMappingTest.java
src/test/resources/scripts/cognito/cognito.groovy
src/test/resources/scripts/cognito/cognito.json
src/test/resources/scripts/default/default-admin.json
src/test/resources/scripts/default/default-nonracf-office-admin.json
src/test/resources/scripts/default/default-office-admin.json
src/test/resources/scripts/default/default.groovy
src/test/resources/scripts/default/default.json

[COG-585](https://osi-cwds.atlassian.net/browse/COG-585)
in case current logged in user is an Office admin his office will be present in principal as singleItemArray adminOffices
- [] Refactoring (No behavioral changes)

Office admin's office is present in principal as adminOffices array

---

build.gradle
src/test/resources/fixtures/idm/permissions/valid.json

- https://osi-cwds.atlassian.net/browse/COG-612
CANS permission added to the list of permissions

COG-612: CANS permission added to the list of permissions

---

src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeImpl.java

https://osi-cwds.atlassian.net/browse/COG-532
Caught and handled exception when login devices are turned off

COG-532 handled case when login devices are turned off

---

api-security/src/main/java/gov/ca/cwds/security/module/AbacMethodInterceptor.java
api-security/src/test/java/gov/ca/cwds/security/ApiSecurityTest.java
api-security/src/test/java/gov/ca/cwds/security/FullyImplementedAuthorizerTest.java
api-security/src/test/java/gov/ca/cwds/testapp/service/FullyImplementedAuthorizerTestService.java
api-security/src/test/java/gov/ca/cwds/testapp/service/FullyImplementedAuthorizerTestServiceImpl.java

- [CANS-388: Fix Null pointer exception](https://osi-cwds.atlassian.net/browse/CANS-388)
Not authorizing a null object

CANS-388. Fix Null pointer exception

---

src/main/java/gov/ca/cwds/idm/IdmResource.java
src/main/java/gov/ca/cwds/idm/service/AuthorizeService.java
src/main/java/gov/ca/cwds/idm/service/AuthorizeServiceImpl.java
src/main/java/gov/ca/cwds/idm/service/IdmService.java
src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
src/main/java/gov/ca/cwds/idm/service/cognito/AuthorizeService.java
src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacade.java
src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeImpl.java
src/test/java/gov/ca/cwds/idm/IdmResourceTest.java
src/test/java/gov/ca/cwds/idm/service/AuthorizeServiceTest.java

https://osi-cwds.atlassian.net/browse/COG-498
Extracted interface for AuthorizeService, renamed contract methods to reflect theirs responsibility,
removed building message logic from AuthorizeService
This is just refactoring

COG-498 AuthorizeService refactoring

---

src/main/java/gov/ca/cwds/idm/service/authorization/AuthorizationServiceImpl.java
src/main/java/gov/ca/cwds/idm/service/authorization/OfficeAdminAuthorizer.java
src/test/java/gov/ca/cwds/idm/service/authorization/AuthorizationServiceImplTest.java
src/test/java/gov/ca/cwds/idm/service/authorization/AuthorizationTestHelper.java
src/test/java/gov/ca/cwds/idm/service/authorization/OfficeAdminAuthorizerTest.java

https://osi-cwds.atlassian.net/browse/COG-498
Implementation for "Office admins will only edit users from their own office"

COG-498 Office admin edit users in CWS-CARES

---

src/main/java/gov/ca/cwds/idm/service/authorization/AuthorizationServiceImpl.java
src/main/java/gov/ca/cwds/util/CurrentAuthenticatedUserUtil.java
src/main/java/gov/ca/cwds/util/UniversalUserTokenDeserializer.java
src/test/java/gov/ca/cwds/idm/service/authorization/AuthorizationServiceImplTest.java

https://osi-cwds.atlassian.net/browse/COG-498
Added "userName" parameter to UniversalUserToken

COG-498 fixed bug when admin can edit himself

---

src/main/java/gov/ca/cwds/idm/service/IdmService.java
src/main/java/gov/ca/cwds/idm/service/OfficeService.java
src/main/java/gov/ca/cwds/idm/service/authorization/AdminActionsAuthorizer.java
src/main/java/gov/ca/cwds/idm/service/authorization/AuthorizationService.java
src/main/java/gov/ca/cwds/idm/service/authorization/AuthorizationServiceImpl.java
src/main/java/gov/ca/cwds/idm/service/authorization/AuthorizationUtils.java
src/main/java/gov/ca/cwds/idm/service/authorization/CalsAdminAuthorizer.java
src/main/java/gov/ca/cwds/idm/service/authorization/CountyAdminAuthorizer.java
src/main/java/gov/ca/cwds/idm/service/authorization/OfficeAdminAuthorizer.java
src/main/java/gov/ca/cwds/idm/service/authorization/StateAdminAuthorizer.java
src/main/java/gov/ca/cwds/idm/service/authorization/UserRolesService.java
src/main/java/gov/ca/cwds/util/CurrentAuthenticatedUserUtil.java
src/main/java/gov/ca/cwds/util/UniversalUserTokenDeserializer.java
src/test/java/gov/ca/cwds/idm/service/authorization/AuthorizationServiceImplTest.java
src/test/java/gov/ca/cwds/idm/service/authorization/OfficeAdminAuthorizerTest.java
src/test/resources/scripts/default/empty_roles.json

https://osi-cwds.atlassian.net/browse/COG-498
Technical debt addressed: mocking static context, UniversalUserTokenDeserializer - user name is mandatory 
This is refactoring

COG-498 Technical debt

---

src/main/java/gov/ca/cwds/idm/IdmResource.java
src/main/java/gov/ca/cwds/idm/dto/UserByIdResponse.java
src/main/java/gov/ca/cwds/idm/service/authorization/AdminActionsAuthorizer.java
src/main/java/gov/ca/cwds/idm/service/authorization/AuthorizationServiceImpl.java
src/main/java/gov/ca/cwds/idm/service/role/implementor/AdminRoleImplementor.java
src/main/java/gov/ca/cwds/idm/service/role/implementor/AdminRoleImplementorFactory.java
src/main/java/gov/ca/cwds/idm/service/role/implementor/AuthorizationUtils.java
src/main/java/gov/ca/cwds/idm/service/role/implementor/CalsAdminAuthorizer.java
src/main/java/gov/ca/cwds/idm/service/role/implementor/CalsAdminRoleImplementor.java
src/main/java/gov/ca/cwds/idm/service/role/implementor/CountyAdminAuthorizer.java
src/main/java/gov/ca/cwds/idm/service/role/implementor/CountyAdminRoleImplementor.java
src/main/java/gov/ca/cwds/idm/service/role/implementor/OfficeAdminAuthorizer.java
src/main/java/gov/ca/cwds/idm/service/role/implementor/OfficeAdminRoleImplementor.java
src/main/java/gov/ca/cwds/idm/service/role/implementor/RoleImplementorFactory.java
src/main/java/gov/ca/cwds/idm/service/role/implementor/StateAdminAuthorizer.java
src/main/java/gov/ca/cwds/idm/service/role/implementor/StateAdminRoleImplementor.java
src/test/java/gov/ca/cwds/idm/IdmResourceTest.java
src/test/java/gov/ca/cwds/idm/service/AuthorizationTestHelper.java
src/test/java/gov/ca/cwds/idm/service/authorization/AuthorizationServiceImplTest.java
src/test/java/gov/ca/cwds/idm/service/role/implementor/CalsAdminRoleImplementorTest.java
src/test/java/gov/ca/cwds/idm/service/role/implementor/CountyAdminRoleImplementorTest.java
src/test/java/gov/ca/cwds/idm/service/role/implementor/OfficeAdminAuthorizerTest.java
src/test/java/gov/ca/cwds/idm/service/role/implementor/OfficeAdminRoleImplementorTest.java
src/test/java/gov/ca/cwds/idm/service/role/implementor/StateAdminRoleImplementorTest.java
src/test/resources/fixtures/idm/get-user/with-cals-externa-worker-role.json
src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-valid-1.json
src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-valid-2.json
src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-valid-3.json
src/test/resources/fixtures/idm/get-user/with-racfid-valid-1.json
src/test/resources/fixtures/idm/get-user/with-racfid-valid-2.json

https://osi-cwds.atlassian.net/browse/COG-669
Fulfill a Roles Dropdown in Edit Mode Only With Possible Values Based on Current Admin Limitation
There is no ability to parametrize test fixtures in case it has only minor differences between tests.
That's why 1,2,3 was added to fixture names. Some template engine should be introduced to get rid of duplicate fixtures

COG-669 Possible Roles Dropdown

---

src/main/java/gov/ca/cwds/config/api/idm/Roles.java
src/main/java/gov/ca/cwds/idm/IdmResource.java
src/test/java/gov/ca/cwds/idm/IdmResourceTest.java
src/test/resources/fixtures/idm/roles/valid.json

- [COG-672: User Roles Dictionary Service](https://osi-cwds.atlassian.net/browse/COG-672)
Added role dictionary as an endpoint service to be used for the frontend

COG-672: User Roles Dictionary Service

---

src/main/java/gov/ca/cwds/idm/IdmResource.java
src/main/java/gov/ca/cwds/idm/service/IdmService.java
src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
src/main/java/gov/ca/cwds/idm/service/authorization/AuthorizationService.java
src/main/java/gov/ca/cwds/idm/service/authorization/AuthorizationServiceImpl.java
src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacade.java
src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeImpl.java
src/test/java/gov/ca/cwds/idm/IdmResourceTest.java

- [COG-646: Resent invitation mail has wrong "Login Email" value](https://osi-cwds.atlassian.net/browse/COG-646)
Changed the userId to user email so that the email will show email address rather than Cognito User Guid.

COG-646: Resent invitation mail has wrong "Login Email" value

---

src/main/java/gov/ca/cwds/idm/dto/User.java
src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
src/main/java/gov/ca/cwds/idm/service/filter/MainRoleFilter.java
src/test/java/gov/ca/cwds/idm/service/filter/MainRoleFilterTest.java
src/test/resources/fixtures/idm/failed-operations/failed-operations-valid.json
src/test/resources/fixtures/idm/get-user/no-racfid-valid.json
src/test/resources/fixtures/idm/get-user/with-racfid-valid-1.json
src/test/resources/fixtures/idm/get-user/with-racfid-valid-2.json

- [COG-702: User's Main Role Determination](https://osi-cwds.atlassian.net/browse/COG-702)
User datamodel, as a part of the contract, contains an array list of roles so it is expected that "main" role (if it is present) will be the first one (and only) in the list.
- [] I have included integration tests

COG-702 Main Role Determination

---

src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
src/test/resources/fixtures/idm/get-users/all-valid.json
src/test/resources/fixtures/idm/get-users/search-valid.json
src/test/resources/fixtures/idm/users-search/valid.json
src/test/resources/fixtures/idm/users-search/yolod.json

- [COG-702: User's Main Role Determination](https://osi-cwds.atlassian.net/browse/COG-702)
Filtering by main role is added to getUsers and searchUsers API operations

Cog 702  Main Role Determination,  getUsers and searchUsers

---

config/default.groovy
src/test/resources/scripts/default/default-admin.json
src/test/resources/scripts/default/default-office-admin.json
src/test/resources/scripts/default/default.groovy
src/test/resources/scripts/default/default.json

- https://osi-cwds.atlassian.net/browse/CANS-711
CANS permissions populated for Supervisor user

CANS-711: supervisor permissions added to JSON

---

docker-perry/Dockerfile-perry.template

Update dockerfile to use alpine linux with oracle jre

Update dockerfile to use alpine

---

config/default.groovy
src/test/java/gov/ca/cwds/service/scripts/DefaultMappingTest.java
src/test/resources/scripts/default/default.groovy
src/test/resources/scripts/default/minimal-default-permissions/auth-no-privilege-and-no-authority.json
src/test/resources/scripts/default/minimal-default-permissions/default-privilege-and-authority.json

- https://osi-cwds.atlassian.net/browse/CANS-710
Non-case carrying worker permissions mapping changed. Minimal default CANS permissions added

CANS-710: non-case carrying worker permissions mapping changed

---

src/main/java/gov/ca/cwds/idm/IdmResource.java
src/main/java/gov/ca/cwds/idm/dto/UserUpdate.java
src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacade.java
src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeImpl.java
src/main/java/gov/ca/cwds/idm/service/cognito/util/CognitoUtils.java
src/test/java/gov/ca/cwds/idm/UpdateUserTest.java
src/test/java/gov/ca/cwds/idm/service/cognito/util/CognitoUtilsTest.java

- [COG-942: change PATCH user service to accept email changes](https://osi-cwds.atlassian.net/browse/COG-942)

COG-942 change PATCH user service to accept email changes

---

src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
src/main/java/gov/ca/cwds/idm/service/OfficeService.java
src/main/java/gov/ca/cwds/idm/service/authorization/AuthorizationServiceImpl.java
src/test/java/gov/ca/cwds/idm/GetUserTest.java
src/test/java/gov/ca/cwds/idm/util/TestCognitoServiceFacade.java
src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-invalid-county-in-cognito.json
src/test/resources/liquibase/cms-data.xml

- [COG-916: Edit is disable for particular user (CWS-worker) when logged in as county-admin](https://osi-cwds.atlassian.net/browse/COG-916)
Login into CARES application as Madera County Administrator
Click on any User
edit the id in URL with 13ed5c07-e05d-4669-a5f2-4bc79845c4ee(User role is CWS Worker, belongs to Madera County)
Expected Result : Edit button is enabled
Actual Result : Edit button is disabled

COG-916 Bug: Edit is disable for particular user (CWS-worker) when logged in as county-admin

---

Jenkinsfile-complete.groovy
config/perry-clustered-dev.yml
docker-perry/entrypoint.sh
src/main/resources/static/login.html

- https://osi-cwds.atlassian.net/browse/DS-1307
Clustered DEV mode  added

DS-1307: CLUSTERED_DEV_MODE added

---

config/default.groovy
src/test/resources/scripts/default/default-admin.json
src/test/resources/scripts/default/default-case-carrying-staff-person.json
src/test/resources/scripts/default/default-office-admin.json
src/test/resources/scripts/default/default.groovy
src/test/resources/scripts/default/default.json
src/test/resources/scripts/default/non-case-carrying/default-no-privilege-and-authority.json
src/test/resources/scripts/default/non-case-carrying/default-privilege-and-authority.json
src/test/resources/scripts/default/non-case-carrying/default-privilege-no-authority.json

- https://osi-cwds.atlassian.net/browse/CANS-829
Default mapping updated. Tests fixed.

CANS-829: Perry permissions mapping adjusted to accommodate CANS 1.1 business rules

---

Jenkinsfile-pull-request.groovy

https://osi-cwds.atlassian.net/browse/FIT-372
Implementing the SemVer for Perry using the shared library. Each PR should be created with a label(Major, Minor or patch)

Added the label checker and removed release parameters

---

build.gradle

https://osi-cwds.atlassian.net/browse/FIT-372

Changed projectVersion to String for SemVer purpose

---

Jenkinsfile-complete.groovy

- [FIT-372: Implement Semantic Versioning Support for Perry](https://osi-cwds.atlassian.net/browse/FIT-372)
Built the SemVer for Perry and tested on the Jenkins with a separate Jenkins job 
http://jenkins.dev.cwds.io:8080/view/perry/job/perry-master-build-testing/
It's a Jenkins file

FIT 372 SemVer For Perry

---

Jenkinsfile-complete.groovy

https://osi-cwds.atlassian.net/browse/FIT-372
added the stage for deploying to pre-int and Integration

Clean up and added the stage for deploying to pre-int and Integration

---

config/perry-dev.yml
config/perry-prod.yml
src/main/java/gov/ca/cwds/PerryApplication.java
src/main/java/gov/ca/cwds/config/SpringAsyncConfiguration.java
src/main/java/gov/ca/cwds/idm/dto/AuditEvent.java
src/main/java/gov/ca/cwds/idm/dto/UserChangeLogRecord.java
src/main/java/gov/ca/cwds/idm/event/ChangeLogEventListener.java
src/main/java/gov/ca/cwds/idm/event/UserCreatedEvent.java
src/main/java/gov/ca/cwds/idm/exception/ChangeLogListenerExceptionHandler.java
src/main/java/gov/ca/cwds/idm/service/AuditLogService.java
src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
src/main/java/gov/ca/cwds/idm/service/IndexRestSender.java
src/main/java/gov/ca/cwds/idm/service/SearchService.java
src/main/java/gov/ca/cwds/idm/service/cognito/AuditProperties.java
src/main/java/gov/ca/cwds/idm/service/retry/IndexRetryConfiguration.java
src/main/java/gov/ca/cwds/util/AuditLogsUtil.java
src/main/java/gov/ca/cwds/util/CurrentAuthenticatedUserUtil.java
src/main/java/gov/ca/cwds/util/UniversalUserTokenDeserializer.java
src/test/java/gov/ca/cwds/idm/BaseIdmIntegrationWithSearchTest.java
src/test/java/gov/ca/cwds/idm/CreateUserTest.java
src/test/java/gov/ca/cwds/idm/service/SearchServiceTest.java
src/test/java/gov/ca/cwds/service/UniversalUserTokenDeserializerTest.java
src/test/java/gov/ca/cwds/util/AuditLogsUtilTest.java

- [COG-1072: User Created Change Log Record](https://osi-cwds.atlassian.net/browse/COG-1072)
COG 1072 User Created Change Log Record. Once the user is created the audit ES index should receive the new event with the type "User Created"
the new section was created in a configuration yaml file: 
`audit:
doraUrl: ${DORA_URL:https://doraapi.integration.cwds.io}
index: ${ES_AUDIT_INDEX:auditevents}
type: ${ES_AUDIT_TYPE:auditevent}`

COG 1072 User Created Change Log Record

---

Jenkinsfile-pull-request.groovy

rearranged the SemVer label check

---

src/main/java/gov/ca/cwds/idm/event/AuditEvent.java
src/main/java/gov/ca/cwds/idm/event/UserChangeLogEvent.java
src/main/java/gov/ca/cwds/idm/event/UserRoleChangedEvent.java

https://osi-cwds.atlassian.net/browse/COG-1097
Sonar bug fix

COG-1097 Sonar bug fix

---

src/main/java/gov/ca/cwds/idm/event/AuditEvent.java
src/main/java/gov/ca/cwds/idm/event/EmailChangedEvent.java
src/main/java/gov/ca/cwds/idm/event/UserChangeLogEvent.java
src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacade.java
src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeImpl.java
src/main/java/gov/ca/cwds/idm/service/cognito/attribute/UpdatedAttributesBuilder.java
src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/AbstractUserAttributeDiffBuilder.java
src/test/java/gov/ca/cwds/idm/UpdateUserTest.java
src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java
src/test/java/gov/ca/cwds/idm/service/IdmServiceImplTest.java

https://osi-cwds.atlassian.net/browse/COG-1099
Added Email Changed Event

COG-1099 Email Changed Event

---

src/main/java/gov/ca/cwds/idm/event/UserChangeLogEvent.java
src/main/java/gov/ca/cwds/idm/event/UserRoleChangedEvent.java

https://osi-cwds.atlassian.net/browse/COG-1099
Event types renaming, transforming role_id to role_name for admin
- [] Refactoring (No behavioral changes)
- [x ] Bug fix (non-breaking change which fixes an issue)

COG-1099 Event types renaming, transforming role_id to role_name for admin

---

src/main/java/gov/ca/cwds/idm/IdmResource.java
src/main/java/gov/ca/cwds/idm/event/EmailChangedEvent.java
src/main/java/gov/ca/cwds/idm/event/PermissionsChangedEvent.java
src/main/java/gov/ca/cwds/idm/event/UserRoleChangedEvent.java

https://osi-cwds.atlassian.net/browse/COG-1099
Event type renamings

COG-1099 event type renaming

---

src/main/java/gov/ca/cwds/idm/event/PermissionsChangedEvent.java
src/main/java/gov/ca/cwds/idm/event/UserEnabledStatusChangedEvent.java
src/main/java/gov/ca/cwds/idm/persistence/ns/entity/Permission.java
src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
src/main/java/gov/ca/cwds/util/IdToNameConverter.java
src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java

https://osi-cwds.atlassian.net/browse/COG-1096
transformed permission ids to permission descriptions, changed account status to disabled/enabled instead of true/false

COG-1096 minor fixes

---

src/main/java/gov/ca/cwds/idm/event/UserEnabledStatusChangedEvent.java

https://osi-cwds.atlassian.net/browse/COG-1096
renamed old and new value for Account Status Changed event

COG-1096 renamed old and new value for Account Status Changed event

---

Jenkinsfile-hotfix.groovy

Hotfix pipeline

---

build.gradle

https://osi-cwds.atlassian.net/browse/COG-1079
removed last_registration_resubmit_time from user table

COG-1079 removed last_registration_resubmit_time from user table

---

src/main/java/gov/ca/cwds/idm/service/TransactionalUserService.java

- [COG-1107: Sonar fix](https://osi-cwds.atlassian.net/browse/COG-1107)
Sonar false positive fix

COG-1107: Sonar fix

---

Jenkinsfile-complete.groovy
Jenkinsfile-pull-request.groovy

https://osi-cwds.atlassian.net/browse/FIT-421
As the new Jenkins configuration was created for a Pull request, the $branch was using default master branch for checkout so removed it and changed the SonarQube to use the Shared library method.

FIT-421 Fixed the PR SonarQube issue

---

build.gradle
config/perry-dev.yml
config/perry-prod.yml
src/main/java/gov/ca/cwds/config/CMSConfiguration.java
src/test/java/gov/ca/cwds/idm/BaseIdmIntegrationTest.java
src/test/java/gov/ca/cwds/idm/service/IdmServiceImplTest.java
src/test/java/gov/ca/cwds/util/LiquibaseUtils.java
src/test/java/gov/ca/cwds/web/PerryDevModeTest.java
src/test/java/gov/ca/cwds/web/PerryMFALoginTest.java
src/test/java/gov/ca/cwds/web/StaffPersonHasAssignmentTest.java

- [COG-1268: DB2 Lockout issue](https://osi-cwds.atlassian.net/browse/COG-1268)
Hikari is introduced as CP provider
SpringBoot version updated to latest 1.x release
connection pool parameters introduced, ready for tuning

COG-1268 DB2 table lock issue

---

config/perry-preview-template.yml

technical PR to apply major label as last build failed and Perry version has updated incorrectly

preview template yml updated

---

src/main/java/gov/ca/cwds/idm/service/AuditEventIndexService.java
src/main/java/gov/ca/cwds/idm/service/AuditEventService.java
src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
src/main/java/gov/ca/cwds/idm/service/UserUpdateRequest.java
src/test/java/gov/ca/cwds/idm/BaseIdmIntegrationWithSearchTest.java
src/test/java/gov/ca/cwds/idm/BaseIdmIntegrationWithUserLogTest.java
src/test/java/gov/ca/cwds/idm/CreateUserTest.java
src/test/java/gov/ca/cwds/idm/ResendInvitationEmailTest.java
src/test/java/gov/ca/cwds/idm/UpdateUserTest.java

https://osi-cwds.atlassian.net/browse/COG-1228
Making events being handled in separate thread

COG-1228 change log events refactoring

---

src/main/java/gov/ca/cwds/idm/service/AuditEventService.java
src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
src/test/java/gov/ca/cwds/idm/IdmNotificationTest.java

COG-1266 persisting the locked event without sending it to dora

---

src/main/java/gov/ca/cwds/idm/persistence/ns/repository/NsUserRepository.java
src/main/java/gov/ca/cwds/idm/service/NsUserServiceImpl.java

- [COG-1302: Authorization Mechanism to Use Postgres User Data](https://osi-cwds.atlassian.net/browse/COG-1302)
Spring "mfa" profile is replaced by "prod" in NsUser servicies
all existing test passed successfully

COG-1302: NsUser servicies fix

---

src/main/java/gov/ca/cwds/idm/persistence/ns/entity/NsUser.java
src/main/java/gov/ca/cwds/idm/persistence/ns/entity/Permission.java
src/main/java/gov/ca/cwds/idm/persistence/ns/entity/UserLog.java

- [COG-1302: Authorization Mechanism to Use Postgres User Data	](https://osi-cwds.atlassian.net/browse/COG-1302)
NS entities are made serializable
All existing tests pass successfully

COG-1302: Serializable is added to NS entities

---

build.gradle
src/main/java/gov/ca/cwds/idm/persistence/ns/entity/NsAuditEvent.java
src/main/java/gov/ca/cwds/idm/service/AuditEventService.java
src/test/java/gov/ca/cwds/idm/persistence/ns/repository/NsAuditEventRepositoryTest.java
src/test/java/gov/ca/cwds/idm/service/AuditEventServiceTest.java

- [COG-1306: AuditEvents Job to Grab Only Failed and Specific Events While Run](https://osi-cwds.atlassian.net/browse/COG-1306)

COG-1306 AuditEvents Job to Grab Only Failed and Specific Events While Run

---

build.gradle

- [COG-1273: Global Admin should not have CALS-admin role in possible roles list](https://osi-cwds.atlassian.net/browse/COG-1273)
Data model version is updated
All existing tests passed successfully

COG-1273: data-model version is updated

---

Jenkinsfile-complete.groovy
Jenkinsfile-release.groovy
build.gradle
docker/DockerfileIntegrationTest
docker/DockerfileIntegrationTestDev
integration-tests/build.gradle
integration-tests/src/test/java/gov/ca/cwds/test/LoginSteps.java
integration-tests/src/test/java/gov/ca/cwds/test/TestCognitoWithMFAMode.java
integration-tests/src/test/java/gov/ca/cwds/test/TestDevMode.java

- [FIT-366 Apply the new shared library for smoke testing to Perry](https://osi-cwds.atlassian.net/browse/FIT-366)
Apply the new shared library for smoke testing to Perry. Allow for login with MFA. Added ability to run smoke and integration tests on preint and integration environments for continuous deployment.
this is for testing

FIT-366 Apply the new shared library for smoke testing to Perry

---

Jenkinsfile-release.groovy
integration-tests/src/test/java/gov/ca/cwds/test/LoginSteps.java

- [FIT-366 Apply the new shared library for smoke testing to Perry](https://osi-cwds.atlassian.net/browse/FIT-366)
Apply the new shared library for smoke testing to Perry. Allow for login with MFA. Added ability to run smoke and integration tests on preint and integration environments for continuous deployment.
this is for testing

Fit 366 apply smoke testing to perry

---

Jenkinsfile-release.groovy

- [FIT-583: Add rollback for Perry release pipeline]https://osi-cwds.atlassian.net/browse/FIT-583
Rollback in case of failed deploy.

fix: FIT-583 Rollback in case of failed deploy.

---

api-security-common/src/main/java/gov/ca/cwds/security/realm/PerryAccount.java

Make PerryAccount class serializable

Make PerryAccount serializable

---

src/main/resources/liquibase/data/permission_data.xml
src/test/resources/fixtures/idm/permissions/valid.json

- [SEAR-652: Add Facility-search-complains permission](https://osi-cwds.atlassian.net/browse/SEAR-652)

SEAR-652 Facility-search-complains permission added

---

Jenkinsfile-complete.groovy

- (https://osi-cwds.atlassian.net/browse/FIT-616)

FIT-616 Update master release pipeline, so it invokes its mgmt Jenkins using https

---

build.gradle

CWDS data model dependency updated

cwds data model dependency updated

---

Jenkinsfile-release.groovy

- [FIT-628:](https://osi-cwds.atlassian.net/browse/FIT-628)
Removes preint deploys

FIT-628: Removes preint deploy

---

src/main/java/gov/ca/cwds/idm/dto/IdmApiCustomError.java
src/main/java/gov/ca/cwds/idm/persistence/cwscms/entity/SystemCodeTable.java
src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
src/main/java/gov/ca/cwds/idm/service/diff/Diff.java
src/main/java/gov/ca/cwds/idm/service/search/BaseSearchIndexService.java
src/main/java/gov/ca/cwds/rest/api/LoginResource.java

CMO-381 fix IV&V top rated issues

---

config/perry-clustered-dev.yml
config/perry-dev.yml
config/perry-prod.yml
src/main/java/gov/ca/cwds/config/JettyConfiguration.java
src/main/java/gov/ca/cwds/config/TraceTrackDenialFilter.java
src/main/java/gov/ca/cwds/config/api/common/BaseApiConfiguration.java
src/main/java/gov/ca/cwds/config/api/idm/PerryIdmAdminConfiguration.java
src/main/java/gov/ca/cwds/config/api/idm/PerryIdmConfiguration.java
src/main/java/gov/ca/cwds/config/mfa/MfaPageConfiguration.java
src/main/java/gov/ca/cwds/service/sso/custom/form/FormLoginConfiguration.java

- [CMO-288: Perry - HTTP TRACE / TRACK Methods Allowed](https://osi-cwds.atlassian.net/browse/CMO-288)
N/A
N/A

CMO-288: Disable Perry HTTP TRACE
