ca-cwds/perry

- build.gradle
- config/cognito.groovy
- src/main/java/gov/ca/cwds/config/api/sp/PerrySpConfiguration.java
- src/main/java/gov/ca/cwds/config/api/sp/SpApiAuthenticationErrorHandler.java
- src/main/java/gov/ca/cwds/config/api/sp/SpApiSecurityFilter.java
- src/main/java/gov/ca/cwds/data/reissue/TokenRepository.java
- src/main/java/gov/ca/cwds/data/reissue/model/PerryTokenEntity.java
- src/main/java/gov/ca/cwds/service/LoginServiceImpl.java
- src/main/java/gov/ca/cwds/service/TokenService.java
- src/main/java/gov/ca/cwds/service/sso/OAuth2Service.java
- src/main/java/gov/ca/cwds/service/sso/SsoService.java
- src/main/java/gov/ca/cwds/service/sso/custom/form/FormService.java
- src/test/java/gov/ca/cwds/service/TokenServiceTest.java
- [CALS-5923: Perry: Replace access token refresh by token introspection during Perry validation flow in Cognito MODE](https://osi-cwds.atlassian.net/browse/CALS-5923)
> CALS-5923: Replace access token refresh by token introspection during Perry validation flow in Cognito MODE

- config/idm.groovy
- src/main/java/gov/ca/cwds/idm/dto/User.java
- src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacade.java
- src/main/java/gov/ca/cwds/idm/service/cognito/CognitoUtils.java
- src/test/java/gov/ca/cwds/idm/IdmResourceTest.java
- src/test/java/gov/ca/cwds/idm/service/cognito/CognitoUtilsTest.java
- src/test/resources/fixtures/idm/get-user/no-racfid-valid.json
- src/test/resources/fixtures/idm/get-user/with-racfid-valid.json
- src/test/resources/fixtures/idm/get-users/all-valid.json
- src/test/resources/fixtures/idm/get-users/search-valid.json
- src/test/resources/fixtures/idm/verify-user/verify-valid.json
- [COG-270: Add Roles to the CAP User datamodel](https://osi-cwds.atlassian.net/browse/COG-270)
As a product owner,
I need the roles attribute to be added to the User datamodel,
So the api will operate with roles attribute in both add and retrieve user flows.
> COG-270 Add Roles to the CAP User datamodel

- src/main/java/gov/ca/cwds/idm/service/SearchService.java
- src/test/java/gov/ca/cwds/idm/service/SearchServiceTest.java
- [COG-383: Update Elastic Search 'users' index using Dora REST webservice during Cognito user insert and update.](https://osi-cwds.atlassian.net/browse/COG-383)
Request content type is fixed
> COG-383: content type is set to APPLICATION_JSON

- src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
- src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacade.java
- src/test/java/gov/ca/cwds/idm/IdmResourceTest.java
- [COG-383: Update Elastic Search 'users' index using Dora REST webservice during Cognito user insert and update.](https://osi-cwds.atlassian.net/browse/COG-383)
Bug fix for User auto-generated fields during create
> COG-383: create in ES fix related to auto-generated fields

- src/main/java/gov/ca/cwds/idm/service/cognito/StandardUserAttribute.java
- src/main/java/gov/ca/cwds/idm/service/cognito/util/CognitoUtils.java
- src/test/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeTest.java
- [COG-459: Email verify not happening for new users created in CAP](https://osi-cwds.atlassian.net/browse/COG-459)
EMAIL_VERIFIED=True added to attributes for user creation in Cognito
> EMAIL_VERIFIED added to attributes for user creation in Cognito

- src/main/java/gov/ca/cwds/service/WhiteList.java
- src/test/java/gov/ca/cwds/service/WhiteListTest.java
- [CANS-385 Perry: support wildcards in callback URLs white list](https://osi-cwds.atlassian.net/browse/CANS-385)
AntPathMatcher was applied for WhiteList which allows using wildcards for callback URLs. Documentation added to Perry Dev Guide.
> CANS-385 Perry: support wildcards in callback URLs white list

- api-security/src/main/java/gov/ca/cwds/security/module/AbacMethodInterceptor.java
- api-security/src/test/java/gov/ca/cwds/security/FullyImplementedAuthorizerTest.java
- api-security/src/test/java/gov/ca/cwds/security/authorizer/FullyImplementedAuthorizer.java
- api-security/src/test/java/gov/ca/cwds/testapp/service/FullyImplementedAuthorizerTestService.java
- api-security/src/test/java/gov/ca/cwds/testapp/service/FullyImplementedAuthorizerTestServiceImpl.java
- [CANS-388N: Null pointer exception instead of 404 error when using invalid assessment id in GET /assessments/{id}](https://osi-cwds.atlassian.net/browse/CANS-388)
Fix for abac results filtering by **the same** nested object
> CANS-388. Fix for abac results filtering by the same nested object

- src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
- src/test/java/gov/ca/cwds/idm/IdmResourceTest.java
- src/test/java/gov/ca/cwds/idm/TestCognitoServiceFacade.java
- src/test/java/gov/ca/cwds/idm/service/IdmServiceImplTest.java
- [COG-561: Ensure no duplicate user in CARES when going from Inactive to Active status](https://osi-cwds.atlassian.net/browse/COG-561)
remove the validation if the user does not have racfid
N/A
N/A
> COG-561: not apply validation if user does not have racfid

- build.gradle
- config/perry-dev.yml
- config/perry-prod.yml
- src/main/java/gov/ca/cwds/data/reissue/TokenRepository.java
- src/main/java/gov/ca/cwds/data/reissue/model/PerryTokenEntity.java
- src/main/java/gov/ca/cwds/service/TokenService.java
- src/test/java/gov/ca/cwds/service/TokenServiceTest.java
- src/test/java/gov/ca/cwds/web/PerryDevModeTest.java
- src/test/java/gov/ca/cwds/web/PerryMFALoginTest.java
- [CANS-366: Perry: Build global session and security token timeout (Token Validate)](https://osi-cwds.atlassian.net/browse/CANS-366)
> CANS-366: Perry: Build global session and security token timeout (Token Validate)

- src/main/java/gov/ca/cwds/idm/service/authorization/AuthorizationServiceImpl.java
- src/main/java/gov/ca/cwds/idm/service/role/implementor/CountyAdminAuthorizer.java
- src/test/java/gov/ca/cwds/idm/IdmResourceTest.java
- src/test/java/gov/ca/cwds/idm/service/AuthorizationTestHelper.java
- src/test/java/gov/ca/cwds/idm/service/authorization/AuthorizationServiceImplTest.java
- [COG-704: County admin should not be able to edit a state admin](https://osi-cwds.atlassian.net/browse/COG-704)
County admin should not be allowed to edit a state admin
> COG-704 County admin should not be able to edit a state admin

- src/main/java/gov/ca/cwds/idm/service/role/implementor/OfficeAdminAuthorizer.java
- src/test/java/gov/ca/cwds/idm/GetUserTest.java
- src/test/java/gov/ca/cwds/idm/service/authorization/AuthorizationServiceImplTest.java
- src/test/resources/fixtures/idm/get-user/with-county-admin-id.json
- src/test/resources/fixtures/idm/get-user/with-state-admin-id.json
- [COG-821: Office admin's ability to view profile of users belonging to other offices in same county](https://osi-cwds.atlassian.net/browse/COG-821)
We will allow an office admin to view the details of other Office, County admins in the SAME county.
> COG-821: Office admin's ability to view profile of users belonging to other offices in same county

- src/main/java/gov/ca/cwds/idm/dto/User.java
- src/test/resources/fixtures/idm/failed-operations/failed-operations-valid.json
- src/test/resources/fixtures/idm/get-user/no-racfid-valid.json
- src/test/resources/fixtures/idm/get-user/with-cals-externa-worker-role.json
- src/test/resources/fixtures/idm/get-user/with-county-admin-id.json
- src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-valid-1.json
- src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-valid-2.json
- src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-valid-3.json
- src/test/resources/fixtures/idm/get-user/with-racfid-and-no-phone-extension.json
- src/test/resources/fixtures/idm/get-user/with-racfid-valid-1.json
- src/test/resources/fixtures/idm/get-user/with-racfid-valid-2.json
- src/test/resources/fixtures/idm/get-user/with-state-admin-id.json
- src/test/resources/fixtures/idm/get-users/all-valid.json
- src/test/resources/fixtures/idm/get-users/search-valid.json
- src/test/resources/fixtures/idm/users-search/valid.json
- src/test/resources/fixtures/idm/users-search/yolod.json
- src/test/resources/fixtures/idm/verify-user/verify-valid.json
- [COG-852: Enrich User's Datamodel with Registration Re-submit DateTime for getUserById Response](https://osi-cwds.atlassian.net/browse/COG-852)
registration_resubmit_date_time is renamed to last_registration_resubmit_date_time
cases with last_registration_resubmit_date_time==null are added
> COG-852 Enrich User's Datamodel with Registration Re-submit DateTime for getUserById Response

- src/main/java/gov/ca/cwds/idm/IdmResource.java
- src/main/java/gov/ca/cwds/idm/service/IdmService.java
- src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
- src/main/java/gov/ca/cwds/idm/service/authorization/AuthorizationService.java
- src/main/java/gov/ca/cwds/idm/service/authorization/AuthorizationServiceImpl.java
- src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeImpl.java
- src/main/java/gov/ca/cwds/idm/service/cognito/util/CognitoUtils.java
- src/test/java/gov/ca/cwds/idm/ResendInvitationEmailTest.java
- src/test/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeTest.java
- [COG-867: Change parameter of resendInvitationEmail API operation from email to User Id](https://osi-cwds.atlassian.net/browse/COG-867)
This task has two goals:
* Keep API consistent by using user Id as key identifying user in all user related operations.
* Spare some additional operations in UI (obtaining email by id) and backend (search by email).
> COG-867 Change parameter of resendInvitationEmail API operation from email to User Id

- integration-tests/src/test/java/gov/ca/cwds/test/TestCognitoMode.java
default login form provided by AWS has been changed so corresponded changes were needed to the XPATH queries in our integration tests
> integration tests fixed

- src/main/java/gov/ca/cwds/idm/service/OfficeService.java
- src/test/java/gov/ca/cwds/idm/OfficesTest.java
- [COG-1065: Office information is not displayed for Global Admins](https://osi-cwds.atlassian.net/browse/COG-1065)
Test Steps:
1. Log into CARES as Global admin
2. Navigate to Manage Users
Expected Result:
1. All columns populated correctly.
2. Ability to filter by Office Name.
Actual result:
1. Office Name is not populated with correct data.
2. Offices are not listed in the Filter by Office drop down
> COG-1065: Office information is not displayed for Global Admins

- src/main/java/gov/ca/cwds/idm/dto/AuditEvent.java
https://osi-cwds.atlassian.net/browse/COG-1097
Changed timestamp format for audit event creation to "yyyy-MM-dd HH:mm:ss"
> COG-1097 changed audit event datetime format to adhere unified pattern

- src/main/java/gov/ca/cwds/idm/event/UserChangeLogEvent.java
- src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java
- [COG-1180: Wrong User Role format in Change Log](https://osi-cwds.atlassian.net/browse/COG-1180)
Roles names instead of Ids in events fixed
> COG-1180 Roles names instead of Ids in events fixed

- src/main/java/gov/ca/cwds/idm/lifecycle/UserLockService.java
- src/test/java/gov/ca/cwds/idm/UserLockTest.java
- [COG-1164: Unlock user as an admin in CWS-CARES - Detail View](https://osi-cwds.atlassian.net/browse/COG-1164)
Removed transaction attribute for unlock
N/A
N/A
> COG-1164: Unlock service implementation

- src/main/java/gov/ca/cwds/idm/service/cognito/attribute/CustomUserAttribute.java
- src/main/java/gov/ca/cwds/idm/service/cognito/util/CognitoRequestHelper.java
- src/test/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeTest.java
- [COG-1164: Unlock user as an admin in CWS-CARES - Detail View](https://osi-cwds.atlassian.net/browse/COG-1164)
Reset Cognito custom attribute custom:numLoginAttempts to "0" after unlocking user
N/A
N/A
> COG-1164: Reset MAX_LOGIN_ATTEMPTS to "0" after unlocking user

- src/main/java/gov/ca/cwds/idm/event/UserCausedChangeLogEvent.java
- src/main/java/gov/ca/cwds/idm/event/UserChangeLogEvent.java
- src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java
- [COG-1152: admin_name and user_name in audit_event should be in "Last Name, First Name" format for all events](https://osi-cwds.atlassian.net/browse/COG-1152)
Format admin_name and user_name as "Last Name, First Name" for all user events
N/A
> COG-1152 - admin_name and user_name in audit_event should be in "Last Name, First Name" format for all events
